[workspace]
members = ["programs/*"]
resolver = "2"
exclude = ["app/api", "app/payment-engine-service"]

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
